export default {
    //  
    CART_AMOUNT_INCREATENT: 'CART_AMOUNT_INCREATENT',
    CART_AMOUNT_DECREATENT: 'CART_AMOUNT_DECREATENT',
    // 
    START_LOADING_POSTS: 'START_LOADING_POSTS',
    POSTS_LOADING_SUCCESS: 'POSTS_LOADING_SUCCESS',
    POSTS_LOADING_FAIL: 'POSTS_LOADING_FAIL'
}